### ISSUE TITLE
Fine-grained customization with CustomResourceDefinitions

### ISSUE THREAD

**Issue by alehechka** [alehechka/kube-secret-sync#14]
A common pattern with client-go applications is to introduce CRDs that the app is able to interface with directly to perform certain operations with them or use them as configuration options. 

Currently, `kube-secret-sync` only gets its configuration from environment variables provided to it in a deployment config. This works perfectly fine in providing blanket rules to the application. For a more fine-grained approach, a new CRD can be created that provides sync rules to specific, individual secrets. 

Possible implementations details:
- CRD Name: `SecretSyncRule`
- CRD can be deployed to any namespace
- By default, the referenced secret must be in the same namespace as CRD
- CRD can reference a secret in a different namespace 
- Environment variable configs will take precedence over CRD (this will encourage sole use of CRDs)
- Config options will be similar to what is available to environment variables
  - Included namespaces (+ regex filtering)
  - Excluded namespaces (+ regex filtering)
  - The referenced secret will be considered syncable (after env var config rules)

Specification:
```yaml
spec:
  secret: 'name-of-secret'
  namespace: 'namespace-of-secret'
  rules:
    namespaces:
      exclude: 
        - kube-system
        - kube-public
      regexExclude: 
        - 'kube[.]*'
      include: 
        - default
      regexInclude: 
        - 'sync-[.]*'
    force: true
```

It may be worth the consideration of making the CRD the only way to define which secrets to sync. This would make the code itself slightly easier because it wouldn't need to mess with the env vars as well as give consumers the more fine-grained controls out-of-the-box.

- Guide on setting up client-go with API for a CustomResourceDefinition: https://www.martin-helmich.de/en/blog/kubernetes-crd-client.html
- Guide on setting up a helm chart: https://docs.bitnami.com/tutorials/create-your-first-helm-chart
